### ISSUE TITLE
Het is niet duidelijk welk niveau een kerndoel heeft

### ISSUE THREAD

**Issue by allardstrijkerslo** [slonl/curriculum-kerndoelen#2]
Bij elk doel zou in de representatie het niveau of niveaus moeten worden getoond. https://opendata.slo.nl/curriculum/api-acpt/v1/uuid/c3e683f2-bc66-457e-84a3-4fd218b034ee/  Een standaard weergave voor een doel zou moeten zijn zoiets als: https://opendata.slo.nl/curriculum/api-acpt/v1/uuid/b6a9ddbb-ff6c-49dd-b9a7-8ab59c09176c/

**Comment by poef** [comment]
Lijkt ondertussen opgelost
